name: webhook
on:
  workflow_dispatch:
    inputs: 
        type:
            description: 'parser type'
            required: true
            default: 'huawei'

env:
  GITHUB_NAME: ${{ secrets.GIT_NAME }}
  GITHUB_EMAIL: ${{ secrets.GIT_EMAIL }}
  ## 佳明配置
  GARMIN_AUTH_DOMAIN: ${{ secrets.GARMIN_AUTH_DOMAIN }}
  GARMIN_EMAIL: ${{ secrets.GARMIN_EMAIL }}
  GARMIN_PASSWORD: ${{ secrets.GARMIN_PASSWORD }}
  GARMIN_START_TIME: ${{ secrets.GARMIN_START_TIME }}

  ## Coros配置
  COROS_EMAIL: ${{ secrets.COROS_EMAIL }}
  COROS_PASSWORD: ${{ secrets.COROS_PASSWORD }}
  COROS_START_TIME: ${{ secrets.COROS_START_TIME }}

jobs:
  sync:
    runs-on: ubuntu-24.04

    steps:
      - name: Show Input
        run: |
          echo ${{ github.event.inputs.type }}
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}  # 使用PAT，有权限写私有仓库
      - name: Debug token
        run: |
          echo "Token starts with: ${{ secrets.PERSONAL_TOKEN }}"
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      # from pdm
      - name: Set Variables
        id: set_variables
        run: |
          echo "PY=$(python -c 'import hashlib, sys;print(hashlib.sha256(sys.version.encode()+sys.executable.encode()).hexdigest())')" >> $GITHUB_OUTPUT
          echo "PIP_CACHE=$(pip cache dir)" >> $GITHUB_OUTPUT
      - name: Cache PIP
        uses: actions/cache@v4
        with:
          path: ${{ steps.set_variables.outputs.PIP_CACHE }}
          key: Ubuntu-pip-${{ steps.set_variables.outputs.PY }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        if: steps.pip-cache.outputs.cache-hit != 'true'
      - name: Create or update a file for testing
        run: |
          # 获取当前时间，确保每次提交内容都不同
          TIMESTAMP=$(date +"%Y-%m-%d %H:%M:%S")
          # 将内容追加到 test-commit.txt 文件
          echo "GitHub Actions ran a test at $TIMESTAMP" >> test-commit.txt
      - name: Push new cookie
        run: |
          git config --local user.email "${{ env.GITHUB_EMAIL }}"
          git config --local user.name "${{ env.GITHUB_NAME }}"
          git add .
          git commit -m 'update garmin activity' || echo "nothing to commit"
          git push || echo "nothing to push"
